/**
 * LGU Services — static catalog and situation groups.
 * Real templates are fetched from Supabase service_templates.
 * This file provides the default catalog and routing data.
 */

import { LguServiceTemplate } from '../types';

export const AERIS_TEAL = '#00C6AE';
export const AERIS_TEAL_LIGHT = 'rgba(0,198,174,0.12)';

// Status display config
export const SERVICE_STATUS_CONFIG: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  pending: { label: 'PENDING', bg: '#FAEEDA', text: '#633806' },
  under_review: { label: 'UNDER REVIEW', bg: '#E6F1FB', text: '#042C53' },
  appointment_scheduled: { label: 'APPT. SCHEDULED', bg: '#E6F1FB', text: '#042C53' },
  docs_requested: { label: 'DOCS REQUESTED', bg: '#EDE9FE', text: '#3B0764' },
  approved: { label: 'APPROVED', bg: '#EAF3DE', text: '#27500A' },
  rejected: { label: 'REJECTED', bg: '#FCEBEB', text: '#501313' },
  issued: { label: 'ISSUED', bg: 'rgba(0,198,174,0.12)', text: '#005049' },
};

// Situation groups — citizen-first grouping
export const SITUATION_GROUPS = [
  {
    id: 'looking_for_work',
    label: 'Looking for work',
    icon: 'briefcase-outline',
    description: 'Documents required for job applications and employment.',
    services: [
      'good_moral',
      'cert_residency',
      'medical_cert',
      'first_time_job_seeker',
      'ptr',
    ],
  },
  {
    id: 'starting_a_business',
    label: 'Starting a business',
    icon: 'storefront-outline',
    description: 'Permits and clearances for business registration.',
    services: [
      'brgy_business_permit',
      'mayors_permit',
      'zoning_cert',
      'sanitary_permit',
      'occupational_permit',
    ],
  },
  {
    id: 'building_renovating',
    label: 'Building or renovating',
    icon: 'construct-outline',
    description: 'Engineering and building permits.',
    services: [
      'building_permit',
      'fencing_permit',
      'demolition_permit',
      'electrical_permit',
      'excavation_permit',
    ],
  },
  {
    id: 'personal_documents',
    label: 'Personal documents',
    icon: 'id-card-outline',
    description: 'Barangay certificates and identity documents.',
    services: [
      'brgy_clearance',
      'cert_residency',
      'indigency_cert',
      'birth_endorsement',
      'cedula',
    ],
  },
  {
    id: 'family_welfare',
    label: 'Family and welfare',
    icon: 'people-outline',
    description: 'Social welfare, senior, and PWD services.',
    services: [
      'senior_citizen_id',
      'pwd_id',
      'solo_parent_id',
      'aics',
      'daycare_enrollment',
      'scholarship',
    ],
  },
  {
    id: 'paying_taxes',
    label: 'Paying taxes and fees',
    icon: 'receipt-outline',
    description: 'Real property tax, cedula, and permit renewals.',
    services: [
      'rpt',
      'cedula',
      'business_permit_renewal',
      'ptr',
      'transfer_tax',
    ],
  },
  {
    id: 'health_services',
    label: 'Health services',
    icon: 'medical-outline',
    description: 'Medical certificates, burial permits, and records.',
    services: [
      'medical_cert',
      'burial_permit',
      'vaccination_records',
    ],
  },
  {
    id: 'environment',
    label: 'Environment',
    icon: 'leaf-outline',
    description: 'Environmental clearances and permits.',
    services: [
      'tree_cutting_permit',
      'garbage_collection',
      'environmental_clearance',
    ],
  },
] as const;

export type SituationGroupId = typeof SITUATION_GROUPS[number]['id'];

// Default service catalog — loaded from Supabase in production.
// This serves as fallback / skeleton data.
export const DEFAULT_SERVICE_CATALOG: LguServiceTemplate[] = [
  {
    templateKey: 'brgy_clearance',
    name: 'Barangay Clearance',
    description: 'Required for employment, business permits, and school enrollment.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'document-text-outline',
    feeAmount: 100,
    feeLabel: 'PHP 100',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['personal_documents'],
  },
  {
    templateKey: 'cedula',
    name: 'Community Tax Certificate (Cedula)',
    description: 'Required for notarial, government, and business transactions.',
    office: "City Treasurer's Office",
    category: 'Documents',
    icon: 'id-card-outline',
    feeAmount: 50,
    feeLabel: 'PHP 50+',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['personal_documents', 'paying_taxes'],
  },
  {
    templateKey: 'good_moral',
    name: 'Good Moral Certificate',
    description: 'Character certification required for job and school applications.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'ribbon-outline',
    feeAmount: 50,
    feeLabel: 'PHP 50',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['looking_for_work'],
  },
  {
    templateKey: 'indigency_cert',
    name: 'Certificate of Indigency',
    description: 'For social welfare assistance, scholarship, and legal aid.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'heart-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['personal_documents', 'family_welfare'],
  },
  {
    templateKey: 'cert_residency',
    name: 'Certificate of Residency',
    description: 'Proof of residence for government and private transactions.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'home-outline',
    feeAmount: 50,
    feeLabel: 'PHP 50',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['personal_documents', 'looking_for_work'],
  },
  {
    templateKey: 'brgy_business_permit',
    name: 'Barangay Business Clearance',
    description: 'Required before applying for a Mayor\'s Permit.',
    office: 'Barangay Hall',
    category: 'Business',
    icon: 'storefront-outline',
    feeAmount: 200,
    feeLabel: 'PHP 200+',
    processingDays: 3,
    requiresKyc: true,
    situationGroups: ['starting_a_business'],
  },
  {
    templateKey: 'mayors_permit',
    name: "Mayor's Business Permit",
    description: 'Annual business operating permit from the city.',
    office: "Business Permit and Licensing Office",
    category: 'Business',
    icon: 'business-outline',
    feeAmount: null,
    feeLabel: 'Varies by business',
    processingDays: 7,
    requiresKyc: true,
    situationGroups: ['starting_a_business'],
  },
  {
    templateKey: 'medical_cert',
    name: 'Medical Certificate',
    description: 'Health clearance for employment, school, or travel.',
    office: 'Rural Health Unit',
    category: 'Health',
    icon: 'medical-outline',
    feeAmount: 100,
    feeLabel: 'PHP 100',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['looking_for_work', 'health_services'],
  },
  {
    templateKey: 'senior_citizen_id',
    name: 'Senior Citizen ID',
    description: 'For citizens 60 years old and above. Entitles to discounts and benefits.',
    office: 'OSCA / CSWD',
    category: 'Welfare',
    icon: 'person-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 5,
    requiresKyc: true,
    situationGroups: ['family_welfare'],
  },
  {
    templateKey: 'pwd_id',
    name: 'PWD Identification Card',
    description: 'For persons with disability. Entitles to 20% discount and other benefits.',
    office: 'PDAO / CSWD',
    category: 'Welfare',
    icon: 'accessibility-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 7,
    requiresKyc: true,
    situationGroups: ['family_welfare'],
  },
  {
    templateKey: 'solo_parent_id',
    name: 'Solo Parent ID',
    description: 'For solo parents under RA 8972. Entitles to benefits and privileges.',
    office: 'CSWD',
    category: 'Welfare',
    icon: 'people-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 5,
    requiresKyc: true,
    situationGroups: ['family_welfare'],
  },
  {
    templateKey: 'rpt',
    name: 'Real Property Tax Payment',
    description: 'Annual real property tax for land, buildings, and improvements.',
    office: "City Treasurer's Office",
    category: 'Taxes',
    icon: 'receipt-outline',
    feeAmount: null,
    feeLabel: 'Based on assessment',
    processingDays: 0,
    requiresKyc: true,
    situationGroups: ['paying_taxes'],
  },
  {
    templateKey: 'birth_endorsement',
    name: 'Birth Certificate Endorsement',
    description: 'Barangay endorsement letter for PSA birth certificate requests.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'document-outline',
    feeAmount: 50,
    feeLabel: 'PHP 50',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['personal_documents'],
  },
  {
    templateKey: 'first_time_job_seeker',
    name: 'First-Time Job Seeker Certification',
    description: 'Under RA 11261. Exempts first-time job seekers from documentary stamp and fees.',
    office: 'Barangay Hall',
    category: 'Documents',
    icon: 'briefcase-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['looking_for_work'],
  },
  {
    templateKey: 'burial_permit',
    name: 'Burial Permit',
    description: 'Required before burial. Issued within 24 hours.',
    office: 'Civil Registrar / RHU',
    category: 'Health',
    icon: 'leaf-outline',
    feeAmount: 0,
    feeLabel: 'Free',
    processingDays: 1,
    requiresKyc: false,
    situationGroups: ['health_services'],
  },
  {
    templateKey: 'building_permit',
    name: 'Building Permit',
    description: 'Required before constructing or renovating any structure.',
    office: "Office of the Building Official",
    category: 'Engineering',
    icon: 'construct-outline',
    feeAmount: null,
    feeLabel: 'Varies by floor area',
    processingDays: 15,
    requiresKyc: true,
    situationGroups: ['building_renovating'],
  },
  {
    templateKey: 'environmental_clearance',
    name: 'Environmental Clearance',
    description: 'Required for construction or business near environmental areas.',
    office: "City Environment and Natural Resources Office",
    category: 'Environment',
    icon: 'leaf-outline',
    feeAmount: null,
    feeLabel: 'Varies',
    processingDays: 10,
    requiresKyc: true,
    situationGroups: ['environment'],
  },
  {
    templateKey: 'ptr',
    name: 'Professional Tax Receipt (PTR)',
    description: 'Annual tax for licensed professionals.',
    office: "City Treasurer's Office",
    category: 'Taxes',
    icon: 'school-outline',
    feeAmount: 300,
    feeLabel: 'PHP 300',
    processingDays: 1,
    requiresKyc: true,
    situationGroups: ['looking_for_work', 'paying_taxes'],
  },
];

// Quick access defaults — most commonly requested. LGU can override in config.
export const QUICK_ACCESS_DEFAULTS: string[] = [
  'brgy_clearance',
  'cedula',
  'good_moral',
  'indigency_cert',
  'mayors_permit',
  'rpt',
];
